"""Generate on-device assets for the ESP32 sketch:
  - firmware/esp32_llm/vocab.h : token id -> raw UTF-8 bytes, so the device just
    Serial.write()s the bytes of each generated token (llama2.c style).
  - firmware/esp32_llm/bpe.h    : byte-level BPE tables (byte -> token id map,
    merge pairs in rank order) so the device can tokenize arbitrary prompt text.
  - prints the prompt token ids for a fixed demo prompt to paste into the sketch.
"""

import os

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
TOK = os.path.join(HERE, "..", "data", "bpe32768.json")
OUT = os.path.join(HERE, "..", "firmware", "esp32_llm", "vocab.h")
OUT_BPE = os.path.join(HERE, "..", "firmware", "esp32_llm", "bpe.h")
PROMPT = "Once upon a time"


def bytes_to_unicode():
    # GPT-2 byte encoding, identical to tokenizers' ByteLevel alphabet: printable
    # ASCII first, then Latin-1 extras, everything else shifted up by 256.
    bs = list(range(ord("!"), ord("~") + 1))
    bs += list(range(ord("\u00a1"), ord("\u00ac") + 1))
    bs += list(range(ord("\u00ae"), ord("\u00ff") + 1))
    cs = bs[:]
    n = 0
    for b in range(256):
        if b not in bs:
            bs.append(b)
            cs.append(256 + n)
            n += 1
    return {b: chr(c) for b, c in zip(bs, cs)}


def main():
    tok = Tokenizer.from_file(TOK)
    V = tok.get_vocab_size()
    vocab = tok.get_vocab()  # token string -> id

    # Raw bytes per token: decode single-id sequences. For the ASCII TinyStories
    # domain this reconstructs text exactly when pieces are concatenated.
    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    with open(OUT, "w") as f:
        f.write("// Generated by src/gen_assets.py -- token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {OUT}: {V} tokens, blob {len(blob)/1024:.0f} KB")

    # BPE tables. Tokenizer layout: id 0 = <|endoftext|>, ids 1..256 = byte
    # tokens (GPT-2 alphabet), merge rank r -> id 257+r (asserted below).
    import json

    raw = json.load(open(TOK, encoding="utf-8"))
    merges = raw["model"]["merges"]  # [[a, b], ...] strings, rank order
    assert len(merges) == V - 257, f"expected {V-257} merges, got {len(merges)}"
    for r, (a, b) in enumerate(merges):
        assert vocab[a + b] == 257 + r, f"merge rank {r} id mismatch"
    merge_a = [vocab[a] for a, _ in merges]
    merge_b = [vocab[b] for _, b in merges]

    b2u = bytes_to_unicode()
    byte_ids = [vocab[b2u[b]] for b in range(256)]
    assert sorted(set(byte_ids)) == list(range(1, 257)), "byte token ids must be 1..256"

    def array(name, vals, ctype):
        with open(OUT_BPE, "a") as f:
            f.write(f"static const {ctype} {name}[{len(vals)}] = {{\n")
            for i in range(0, len(vals), 16):
                f.write("  " + ",".join(str(v) for v in vals[i:i+16]) + ",\n")
            f.write("};\n")

    with open(OUT_BPE, "w") as f:
        f.write("// Generated by src/gen_assets.py -- byte-level BPE tokenizer tables.\n")
        f.write("// Merge rank r produces token id 257+r. Pair ids index the vocab.\n")
        f.write("#ifndef BPE_H\n#define BPE_H\n")
        f.write(f"#define BPE_N_MERGES {len(merges)}\n")
        f.write("// byte value -> token id (1..256)\n")
        f.write(f"static const unsigned short BPE_BYTE_TO_ID[256] = {{\n")
        for i in range(0, 256, 16):
            f.write("  " + ",".join(str(v) for v in byte_ids[i:i+16]) + ",\n")
        f.write("};\n")
    array("BPE_MERGES_A", merge_a, "unsigned short")
    array("BPE_MERGES_B", merge_b, "unsigned short")
    with open(OUT_BPE, "a") as f:
        f.write("#endif\n")
    print(f"wrote {OUT_BPE}: {len(merges)} merges, byte map 256 entries")

    ids = tok.encode(PROMPT).ids
    print(f'prompt "{PROMPT}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")
    print("\nPaste into the sketch:")
    print(f"static const int PROMPT_IDS[] = {{{', '.join(map(str, ids))}}};")


if __name__ == "__main__":
    main()
